apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microservices-demo-prod
commonLabels:
  variant: prod

resources:
  - ../base

images:
  - name: cartservice
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/cartservice
    newTag: v0.10.3
  - name: checkoutservice
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/checkoutservice
    newTag: v0.10.3
  - name: currencyservice
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/currencyservice
    newTag: v0.10.3
  - name: emailservice
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/emailservice
    newTag: v0.10.3
  - name: frontend
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/frontend
    newTag: v0.10.3
  - name: paymentservice
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/paymentservice
    newTag: v0.10.3
  - name: productcatalogservice
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/productcatalogservice
    newTag: v0.10.3
  - name: recommendationservice
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/recommendationservice
    newTag: v0.10.3
  - name: shippingservice
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/shippingservice
    newTag: v0.10.3

replicas:
  - name: cartservice
    count: 2
  - name: checkoutservice
    count: 2
  - name: currencyservice
    count: 2
  - name: emailservice
    count: 2
  - name: frontend
    count: 2
  - name: paymentservice
    count: 2
  - name: productcatalogservice
    count: 2
  - name: recommendationservice
    count: 2
  - name: shippingservice
    count: 2
